#!/usr/bin/python 
import os, sys

FORMAT= """
; Summary: Autogenerated Rule List
; Author: phoeagon AT github
; URL: http://github.com/phoeagon/china-whitelist-switchy

#BEGIN

[RegExp]
%s

#END
"""

domain_lists = [x.strip() for x in sys.stdin.readlines()]
print FORMAT % ("\n".join(domain_lists))
